# Quantum Analogues of Boolean Analysis 
## Boolean function algebra 
### Binary domain {-}
In addition to O'Donnell's formalism in sections \@ref(Sec1) and \@ref(Sec2), 
we see that the space of boolean functions $L^2(\P^n)$ 
is in fact a finite freely-generated Hilbert algebra with $n$ generators $x_j\in L^2(\P^n)$ 
(with some convenient notation overloading) 
\[ 
    x_i(x) = x_i, \quad x_i:\P^n\to \C
\] 
Scalar multiplication and addition are defined in the most obvious ways, 
and algebraic multiplication given by 
\begin{equation}
    [x_i, x_j] = 0, \quad x_i^2 = 1
    (\#eq:booleanAlgebra)
\end{equation}
Given an algebraic element $f$, its behavior as a boolean function is retrievable by 
\begin{equation}
    f(x) = 2^n\la f, I_x\ra = \sum_y f(y) \prod \df{1+x_jy_j}{2}
    (\#eq:booleanDecomp)
\end{equation}
Note that the crucial $x_i^2=1$ arises from the algebraic structure of $\P^n$. 
The generators generate the bases $(\chi_J)$ of $L^2(\P^n)$ 
with $2^n$ elements orthonormal w.r.t. the inner product 
\[ 
    \la f, g\ra = \Exp_{\mbf x\sim \P^n} [f(\mbf x)^* g(\mbf x)]
\] 
There exists derivative operator defined by its generator action, 
Leibniz rule, and linearity 
\[ 
    \pd i \chi_j = \delta_{ij}, \quad \pd i (fg) = (\pd i f)g + f(\pd i g)
\] 

### General domain {-}


## Pauli algebra 
Our starting point is recognizing that equation \@ref(eq:booleanAlgebra) is 
exactly the commutation relation of the Pauli basis $(X_j)$ or $(Z_j)$. 
We argue that $(Z_j)$ is the quantum counterpart directly associated with the computational 
basis. Define the "classical" boolean function $\tilde \rho:\P^n\to \R$ 
associated with a quantum state $\rho$ to be the probability of observing $|x\ra$ 
(note that we are using the $\P=\pm 1$ labeling of the computational basis), then 
\[ 
    \tilde \rho(x) = \Pr(x|\rho) = \la x|\rho|x\ra = \tr\left(\rho \prod \df{1+x_j Z_j}{2}\right)
\] 
Comparing this with the classical counterpart \@ref(eq:booleanDecomp) suggests that 
$x_j\mapsto Z_j$. 

:::{.definition name="Pauli quantization of boolean function"}
Given a classical boolean function $f$, its Pauli quantization is the 
diagonal quantum state $\rho_f\in \Hi_n$ specified by 
\[ 
    \la x|\rho|x\ra = f(x)
\] 
This results in the following embedding of boolean function algebra into 
the Pauli algebra $\P_n$ 
\[ 
    x_j \mapsto Z_j, \quad \la f, g\ra = \Exp_{\mbf x}[f(\mbf x)g(\mbf x)] \mapsto 
    \la \rho_f, \rho_g\ra = \df 1 {2^n} \tr(\rho_f\rho_g)
\] 
The full quantum algebra $\P_n$ is generated by introducing $n$ more 
involutary generators $(X_j)$ such that 
\[ 
    [Z_j, X_k] = 2\delta_{jk}Z_jX_j, \quad [X_j, X_k] = 0, \quad X_j^2 = 1
\] 
:::

## Majorana algebra 
Another perspective on the similarity between quantum and classical computation is 
replacing the commutation relation in \@ref(eq:booleanAlgebra) with anti-commutation. 
However, there appears to be no canonical way of doing so. 

:::{.definition name="Majorana algebra"}
The Majorana algebra is the Clifford algebra $\Clif_{2n}$ over $2n$ generators such that 
distinct generators anti-commute 
\[
    \{\gamma_j, \gamma_k\} = \delta_{jk}, \quad \gamma_j^2 = 1
\] 
:::