---
title: "Algebraic Analysis of Classical and Quantum Computation"
author: "Nicholas Lyu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [refs.bib]
biblio-style: "numeric"
split_bib: yes
link-citations: true
---

\usepackage{cancel}
\newcommand{\pd}[1]{\partial_{#1}}

\newcommand{\mbb}{\mathbb}
\newcommand{\mbf}{\mathbf}
\newcommand{\mrm}{\mathrm}
\newcommand{\mca}{\mathcal}
\newcommand{\mfk}{\mathfrak}

\newcommand{\tr}{\mrm{tr}} 
\newcommand{\df}{\dfrac}
\newcommand{\la}{\langle}
\newcommand{\ra}{\rangle}
\newcommand{\dag}{\dagger}

\newcommand{\Cl}{\mca C}
\newcommand{\Gr}{\mca G}
\newcommand{\Pf}{\mrm{Pf}}
\newcommand{\Pa}{\mca P}

\newcommand{\poly}{\mrm{poly}}
\newcommand{\B}{\mca B}
\newcommand{\P}{\mca P}
\newcommand{\R}{\mbb R}
\newcommand{\C}{\mbb C}
\newcommand{\F}{\mbb F}
\newcommand{\sgn}{\mrm{sgn}}

\newcommand{\Exp}{\mbb E}
\newcommand{\Var}{\mrm{Var}}
\newcommand{\Cov}{\mrm{Cov}}
\newcommand{\dist}{\mrm{dist}}
\newcommand{\maj}{\mrm{Maj}}
\newcommand{\Tribes}{\mrm{Tribes}}
\newcommand{\Inft}{\mrm{Inf}_\Sigma}
\newcommand{\Inf}{\mrm{Inf}}
\newcommand{\sens}{\mrm{sens}}
\newcommand{\Lap}{\mrm{L}}



# Preface {-}
Reading notes and select exercise solutions for 
Ryan O'Donnell's book _Analysis of Boolean functions_ 
[@o2014analysis]. 

In addition to being a rich field of computer science in its own right, 
the fourier analysis of boolean functions provide a classical basis 
for the fourier analysis of quantum computation. 

The space of boolean functions $f(x_1, \cdots, x_n)$ 
over $n$ inputs form a freely generated algebra 
in which the generators $x_1, \cdots x_n$ are involutary, commutative, 
and generate an orthonormal basis. 
Subtly generalizing these constraints yield the full qubit algebra: 

- Replacing commutativity over $x_1, \cdots, x_{2n}$ 
    with _anti-commutativity_ yields the majorana 
    algebra over a finite number of modes, 
    or equivalently the qubit algebra under the Jordan-wigner transform. 
- Supplementing $x_1, \cdots, x_{2n}$ with $p_1, \cdots p_{2n}$ 
    such that $[x_i, p_j] = \delta_{ij} x_ip_j$ corresponds to the Pauli 
    algebra with $x_i \mapsto X_i, p_i\mapsto Z_i$. 

These notes are organized as follows

1. Section \@ref(Sec1) corresponds to Chapters 1 & 8 of the book, introducing 
    fourier concepts with boolean functions then generalizing to other domains. 
2. Section \@ref(Sec2) expores the stability and dependence of boolean functions. 

## Notation {-}

- $\P=\{\pm 1, \times\}$ for parity, and $\B=(\{0, 1\}, +)$ for boolean values.  
- $[n] \equiv \{1, \cdots, n\}$, occasionally $\{0, \cdots, n-1\}$ depending 
    on context. 
- $\Delta(x, y)=|\{i|x_i\neq y_i\}|$ denotes the Hamming distance. 
- $A\Delta B$ denote the symmetric difference $(A-A\cap B)\cup (B-A\cap B)$. 
- Boldface letters like $\mbf x$ denote random variables, drawn from a uniform 
    distribution over their domain unless otherwise specified. 
- Under the mapping $(0, 1)$ corresponding to false, true, the representation of 
    truth values in $\P$ is somewhat counter-intuitively $(-1, 1)\mapsto$ true, false. 
- Given a bitstring $x$ and index $i$, $x^{\oplus i}$ denotes $x$ with the $i$-th index 
    negated. Similarly, $x^{i\mapsto b}$ denotes $x$ with the $i$-th index replaced by $b$.
- Let $E$ denote an event, for example, $a=b$. Then $1_E$ denotes the indicator random variable 
    which is $1$ when the event is true, and $0$ otherwise. 